language: node_js
node_js:
    - "12"
dist: xenial

cache: npm

env:
    - TERM=dumb

script:
    - npm ci
    - npm run build

deploy:
    - provider: script
      script: 
        - npm version patch --no-get-tag-version
        - npm ci
        - npm run build
        - npm run publish
      on:
        branch: master
    